### PR TITLE
reviewing plot_bivariate functionality take two

### PR DESCRIPTION
**Pull request by jrosen48**

### CODE REVIEW

**Comment by cjvanlissa** [comment]
Good stuff! Two more changes we might implement:
1) Remove the legacy functions (now, they result in a message about the change to the new version)
2) Can we change the default setting for `plot_profiles(add_line = FALSE)`? In my presentations about LPA, I always talk about uninformative graphs, and criticize the lines used for profile plots because they don't convey any information. And then our own plot also includes them by default ;)

**Comment by jrosen48** [comment]
On board with both of these! Thanks sir.

Also, tagging Dan in here. Dan is interested in working on the theming for the plots. Here is from an earlier convo:

packages should do one of two things with figures:

-          Make them as generic as possible, providing the user the full range to customize them easily. For example, don’t impose any themes or color palettes. OR

-          Utilize every known best practice in the book in terms of human perception for the given figs.
From my perspective, tidyLPA is currently somewhere in between on these. For example, the box plots are currently colored by class, but  generally we’re better at perceiving solid shapes, so I would suggest changing this to a fill and dodging the box plots. Alternatively, if you want to make it as general as possible, so the user can customize it easier, you may want to think about not imposing a theme and a color scheme. For example (and I could be wrong on this) I think if I added `+ scale_color_brewer(palette = “Dark2”)` to change the color from the Viridis scheme, I would get an error about there being two color mappings.

You also could have two functions, if you wanted with one called something like plot_profiles and the other plot_fancy_profiles or something along those lines. Or maybe plot_😎_profiles….

**Comment by datalorax** [comment]
Thanks Josh! I will hopefully try to work on this some in the coming week or so and submit a PR for you to see what you think.

**Comment by jrosen48** [comment]
that last commit was due to conflicts from rendering the site again

**Comment by jrosen48** [comment]
merged this, as these were approved (apart from two minor changes I just made - to remove a commented out line and to add a space to the start-up message) and start a new PR to address the two issues mentioned above (removing deprecated functionality and changing the default for `plot_profiles()`

**Comment by jhaltiga** [comment]
> 
> 
> Reviewed these changes, all looks good. Thank you for the additional examples! Two more changes we might implement:
> 
>     1. Remove the legacy functions (now, they result in a message about the change to the new version)
> 
>     2. Can we change the default setting for `plot_profiles(add_line = FALSE)`? In my presentations about LPA, I always talk about uninformative graphs, and criticize the lines used for profile plots because they don't convey any information. And then our own plot also includes them by default ;)

C. J. can you elaborate on why you find lines in profile plots uninformative if they provide means for indicators by class? Very interested to hear more.

**Comment by cjvanlissa** [comment]
> C. J. can you elaborate on why you find lines in profile plots uninformative if they provide means for indicators by class? Very interested to hear more.

@jhaltiga A mean is a point estimate, and in our plots, is indicated by a point. Our plots show means for different classes across different variables. The different variables are confined to different columns, and class membership across the variables is indicated by the shape of the point, and in the color version, also by the color. Thus, all information that should be conveyed by the profile plot is already conveyed without the line.

Now, to the line itself. Visually, a line implies continuity. When you draw a line that connects the points across variables, this raises questions such as: What is the meaning of space between the variables? Can we interpret a trend from one variable mean to the next variable mean? The answers are: The space between the variables has no meaning; in fact, they are just plotted in the same figure to save space, and no, we cannot interpret the trend from one variable mean to the next, unless the variables are measured on the same scale, we have established measurement invariance, and there is a logical progression in time. In which case we should be using growth mixture modeling.

**Comment by jhaltiga** [comment]
> 
> 
> > C. J. can you elaborate on why you find lines in profile plots uninformative if they provide means for indicators by class? Very interested to hear more.
> 
> @jhaltiga A mean is a point estimate, and in our plots, is indicated by a point. Our plots show means for different classes across different variables. The different variables are confined to different columns, and class membership across the variables is indicated by the shape of the point, and in the color version, also by the color. Thus, all information that should be conveyed by the profile plot is already conveyed without the line.
> 
> Now, to the line itself. Visually, a line implies continuity. When you draw a line that connects the points across variables, this raises questions such as: What is the meaning of space between the variables? Can we interpret a trend from one variable mean to the next variable mean? The answers are: The space between the variables has no meaning; in fact, they are just plotted in the same figure to save space, and no, we cannot interpret the trend from one variable mean to the next, unless the variables are measured on the same scale, we have established measurement invariance, and there is a logical progression (e.g., in time - in which case we should be using growth mixture modeling).

re: your 2nd paragraph, while I agree with everything you say, I wonder how many really see the plot this way if they are aware of what the plot is graphing in the first place. It is not a growth situation in a latent profile scenario (or a case of longitudinal MI which growth implies), so this should be understood or communicated to the viewer from the outset that the space between variables naturally has no meaning. That being said, your first point re: the mechanics of the tidyLPA plot mechanics already conveying what would be redundant information via the line is compelling enough for me.

**Comment by cjvanlissa** [comment]
I don't disagree that the plot *can* be interpreted correctly, but I consider it good practice to use clear visual communication. For further substantiation, check out the Grammar of Graphics (https://www.springer.com/gp/book/9780387245447) or other data visualization books, e.g., http://socviz.co/

**Comment by jhaltiga** [comment]
> 
> 
> I don't disagree that the plot _can_ be interpreted correctly, but I consider it good practice to use clear visual communication. For further substantiation, check out the Grammar of Graphics (https://www.springer.com/gp/book/9780387245447) or other data visualization books, e.g., http://socviz.co/

That's fair bro. I was just wanting to get a sense for your thinking which makes good sense and is useful. I try to approach visuals in a bit less of a 'best practice' framework depending on my preference, but I agree here it is warranted given end-user scale.

**Comment by cjvanlissa** [comment]
Another concern is that I've been giving lectures about best practices in visualization, especially for mixture models, and then I always have to give a disclaimer about this plot :p So it would be nice to not have to do that anymore

**Comment by jhaltiga** [comment]
> 
> 
> Another concern is that I've been giving lectures about best practices in visualization, especially for mixture models, and then I always have to give a disclaimer about this plot :p So it would be nice to not have to do that anymore

For sure! If you have any slides of lectures on visualization for mixtures you'd be willing to share, I'd be interested to see your thoughts! My best.

**Pull request merged**
