### PR TITLE
Fix for Mclust models that fail

### PR DESCRIPTION
**Pull request by cjvanlissa**
Here's a fix for Ricardo's difficulties. Josh, can you test these functions for both Mplus and Mclust?

### CODE REVIEW

**Comment by jrosen48** [comment]
Yes, will do. Sorry, I didn't see this until now. My GitHub notifications were messed up (but are fixed for subsequent issues/PRs!).

**Comment by jrosen48** [comment]
Nice, this worked for me.

Two questions:

1. Should we print a message that a particular model did not estimate/did not converge/that an error occurred?

2. At present, when a model is estimated but does not converge, a blank row is printed in the output: thoughts on a) removing the row from the output, b) adding another column with a variable to indicate that an error occurred, or c) adding NA for all of the possible values?

**Comment by jrosen48** [comment]
@cjvanlissa tagging you on this re: 2 questions above.

**Comment by cjvanlissa** [comment]
I think it already does this.. only the print method replaces NA with blank space. The summary function shows an extra column to indicate which models had errors.

**Pull request merged**
