### PR TITLE
Correctly pass dots to Mclust functions

### PR DESCRIPTION
**Pull request by cjvanlissa**
This addresses issue #160 .

### CODE REVIEW

**Comment by cjvanlissa** [comment]
@joshuarosenberg @jrosen48  please check

**Comment by cjvanlissa** [comment]
@joshuarosenberg @jrosen48 could you please check/test this branch?

**Comment by jrosen48** [comment]
yes will do

**Comment by jrosen48** [comment]
checked out this branch and tested - good to go! updating the version number and submitting to CRAN. Thank you @cjvanlissa for all of your work on this (and everything else that has to do with the package!)

**Comment by jrosen48** [comment]
this has the happy side-effect of being an R version 4.0 update

**Pull request merged**
