### PR TITLE
Addressing minor issues

### PR DESCRIPTION
**Pull request by jrosen48**
This addresses the two issues @cjvanlissa raised in #148. I also removed the vignette documenting the major changes.

### CODE REVIEW

**Comment by jrosen48** [comment]
This seems to have failed due to undefined exports (functions exported via the namespace but without any code to define them?)? I think this is related to #146 in that re-running `devtools::document()`/`devtools::check()` may address it? Not sure.

**Comment by cjvanlissa** [comment]
If you check the build history, you can see where it broke:

https://travis-ci.org/data-edu/tidylpa/builds

My fork is still passing: https://travis-ci.org/cjvanlissa/tidyLPA

**Comment by jrosen48** [comment]
Yeah, I gotcha. I just can't run those functions necessary to address this; I *think* possibly because of #146.

**Comment by cjvanlissa** [comment]
> re-running `devtools::document()`/`devtools::check()` may address it? Not sure.

Yes, certainly. You removed the R-functions but did not roxygenize afterwards! You can set your Rstudio project to always compile the package documentation upon Build, or manually run the commands you mention.

**Comment by cjvanlissa** [comment]
Give me a minute

**Pull request merged**
