### PR TITLE
Fix densities

### LINKED ISSUE #168: BUG: plot_density no longer gives correct total density
My best guess is that this is due to a change in ggplot2, because older versions of tidyLPA also no longer work. Must be fixed

### PR DESCRIPTION
**Pull request by cjvanlissa**
closes #168

### CODE REVIEW

**Comment by cjvanlissa** [comment]
@joshuarosenberg could you test the changes as well please?

**Comment by jrosen48** [comment]
Tested this, and it worked really beautifully.

**Comment by jrosen48** [comment]
okay to merge?

**Comment by cjvanlissa** [comment]
@joshuarosenberg the picture you shared is either made with an old version, or it's still broken. If you look closely, you see that each of the densities is rescaled. The colored densities should make up parts of the black "total" line. Could you let me know which is the case?

**Comment by jrosen48** [comment]
Oops, sorry, I had not built the package after checking out the branch. I think this is working; how does this look?

``` r
library(tidyLPA)
#> You can use the function citation('tidyLPA') to create a citation for the use of {tidyLPA}.
#> Mplus is not installed. Use only package = 'mclust' when calling estimate_profiles().
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.6.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

models_4_5 <- pisaUSA15[1:100, ] %>%
  select(broad_interest, enjoyment, self_efficacy) %>%
  single_imputation() %>%
  estimate_profiles(models = 1,
                    n_profiles = c(4, 5))
#> The 'variances'/'covariances' arguments were ignored in favor of the 'models' argument.

models_4_5 %>% 
  plot_density()
```



<sup>Created on 2020-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cjvanlissa** [comment]
It's correct! Is the plot_bivariate() working too?

**Comment by jrosen48** [comment]
I think so --- looks good to you?

``` r
library(tidyLPA)
#> You can use the function citation('tidyLPA') to create a citation for the use of {tidyLPA}.
#> Mplus is not installed. Use only package = 'mclust' when calling estimate_profiles().
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.6.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

models_4_5 <- pisaUSA15[1:100, ] %>%
  select(broad_interest, enjoyment, self_efficacy) %>%
  single_imputation() %>%
  estimate_profiles(models = 1,
                    n_profiles = 4)
#> The 'variances'/'covariances' arguments were ignored in favor of the 'models' argument.

models_4_5 %>% 
  plot_bivariate()
#> Warning in diag(vars): NAs introduced by coercion
```



<sup>Created on 2020-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Pull request merged**
